services:
  database:
    image: 'postgres:11.16-alpine3.16'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: factfinder-user
      POSTGRES_PASSWORD: factfinder-password
      POSTGRES_DB: factfinder-local
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  layers:
    image: tangoyankee/labs-layers-api:1.0.0
    ports:
      - 3000:3000
    command: yarn run dev
  api:
    build: .
    depends_on:
      - database
    command: yarn run dev
    ports:
      - 3001:3001
    env_file:
      - .env
