version: "3"
services:
  # The name of our service is "database"
  # but you can use the name of your choice.
  # Note: This may change the commands you are going to use a little bit.
  database:
    # Official Postgres image from DockerHub (we use the last version)
    image: "postgres:latest"

    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    # Note: You are free to change your computer's port,
    # but take into consideration that it will change the way
    # you are connecting to your database.
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: labs_user # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: labs_user_pw # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: factfinder_db # The PostgreSQL default database (automatically created at first launch)