CREATE SCHEMA IF NOT EXISTS :SCHEMA_NAME;
DROP TABLE IF EXISTS :SCHEMA_NAME.:"TABLE_NAME";

CREATE TEMP TABLE tmp (
    year text,
    geoid text,
    variable text,
    "value" double precision
);

\COPY tmp FROM PSTDIN WITH DELIMITER ',' CSV HEADER;

DROP TABLE IF EXISTS :SCHEMA_NAME.:"TABLE_NAME";
SELECT * INTO :SCHEMA_NAME.:"TABLE_NAME" FROM tmp;