name: CI

on:
  push:

jobs:
  test:
    name: Testing ...
    runs-on: ubuntu-20.04
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
    services:
      db:
        image: postgis/postgis:11-3.0-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'
      - run: yarn install
      - run: yarn migrate
      - run: yarn test