name: migrate

on:
  push:
    branches:
      - 'pratishta/exp-gha-migration'

jobs:
  update:
    name: Data update...
    runs-on: ubuntu-22.04
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install psql
        run: |
          sudo apt install curl ca-certificates
          sudo install -d /usr/share/postgresql-common/pgdg
          sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
          sudo sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt update
          sudo apt -y install postgresql
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install node dependencies
        run: npm ci
      - name: ETL
        run: npm run migrate